luxonis/oak-examples

gen2-camera-demo/main.py, gen2-camera-demo/projector_3d.py, gen2-camera-demo/requirements.txt
StereoDepth configuration options:
```
lrcheck  = True   # Better handling for occlusions
extended = False  # Closer-in minimum depth, disparity range is doubled 
subpixel = True   # Better accuracy for longer distance, fractional disparity 32-levels
```
If one or more of the additional depth modes (lrcheck, extended, subpixel) are enabled, then:
- depth output is FP16. TODO enable U16.
- median filtering is disabled on device. TODO enable.
- with subpixel, either depth or disparity has valid data.
Otherwise, depth output is U16 (mm) and median is functional. But like on Gen1, either depth or disparity has valid data. TODO enable both.
Select one pipeline to run:
```
#pipeline, streams = create_rgb_cam_pipeline()
#pipeline, streams = create_mono_cam_pipeline()
pipeline, streams = …
```
=> Gen2 Color/MonoCamera and StereoDepth example

point-cloud-projection/main.py
I failed to recognize that it wasn't supported and spent a little time to run this demo on RPi. I tried to compile Open3d for RPi 3B. Adding this disclaimer might save others time.
=> Added disclaimer for RPi

gen2-color-isp-raw/main.py, gen2-color-isp-raw/requirements.txt
Example app for IMX378 ColorCamera streaming at full resolution / 12MP (4056x3040):
- `isp` - YUV420p uncompressed frames, processed by ISP
- `raw` - BayerBG (R_Gr_Gb_B), as read from sensor, 10-bit packed
One or both streams can be enabled. By default both are enabled (note this slows down FPS, using more USB traffic).
Install the depthai library: `python3 -m pip install -r requirements.txt`
then run `python3 main.py`
User interaction:
- press `c` to capture a set of frames from the enabled streams. Will be saved as `.png` images, as well as YUV420p and unpacked 16bit RAW10 (those can be opened with a viewer like `vooya`).
- press `q` to quit the app.
=> Add gen2-color-isp-raw experiment

collecting-training-data/main.py
This PR fixes the incorrect handling of `-af` parameter (when it was missing). Reported [here](https://github.com/luxonis/depthai-experiments/issues/3#issuecomment-771649354)
=> Fix -af flag handling

gaze-estimation/main.py, gaze-estimation/requirements.txt
This PR resolves https://github.com/luxonis/depthai-experiments/issues/54
Includes a FW fix of libusb, threads are not daemons anymore, are gracefully joined.
The device object is destroyed before joining the threads, which causes blocking calls of `get()` to throw RuntimeError. This is then caught and handled properly
[Tested on Linux](https://youtu.be/jPSHYufs8wY) - works, no system errors
[Tested on Mac](https://youtu.be/GfPDqfyvOlY) - works, no system errors nor dialog boxes
=> Fix threading issue

gen2-class-saver-jpeg/README.md, gen2-class-saver-jpeg/main.py, gen2-class-saver-jpeg/requirements.txt
This example demonstrates how to run MobilenetSSD and collect images of detected objects, grouped by detection label.
After running this script, DepthAI will start MobilenetSSD, and whenever it detects objects, it will add a dataset entry
Dataset is stored under `data` directory, and a main dataset file is located under `data.dataset.csv`.
For each detected object, a new dataset entry is created, with each entry having files with a precise purpose:
- `timestamp` uses `int(time.time() * 10000)` to store a timestamp of the capture. **Please note** that this value can be duplicated, if multiple objects are detected on a single image
- `label` is a human-readable label of the detected object
- `left`, `top`, `right`, `top` are object bounding box coordinates
- `raw_frame` represents a path to …
=> Add Gen2 Class Saver (JPEG)

gen2-ocr/main.py
One of our users reported an issue with detecting "0" (number) using the OCR example. I was able to reproduce it below
I analyzed the decoding code and found a check `t[i] == 0` that excluded the detection, but it was incorrect. The fill value for empty detections is in fact `36`, which resolves to `#` character after decoding - which we exclude in the next line.
With this PR, the detection of "0" (number) works correctly
=> update OCR example to fix "0" detection problem

collision-avoidance/main.py
Initially, the main Frame and the bird eye view would flicker a lot on Raspberry Pi, due to the same "Frame" name with the other `moveWindow` frame. Updated it and a minor change.
=> Collision Avoidance minor change

gen2-age-gender/main.py, gen2-age-gender/requirements.txt
Now uses script node to decode 1st stage NN (face detection) and to control the imageManip to crop the frame for input into the 2nd stage NN (age/gender recognition).
This experiment crops the initial high-res input image (1080x1080), based on the detection of the NN. This was requested by our user on [discord](https://discord.com/channels/790680891252932659/795743863519576105/870344843702972458). Unfortunately the 2nd stage NN (age-gender-recognition) required 62x62 input image, not a high-quality one, otherwise this feature would be much more visible&useful.
Result img:
=> Age gender refactor

gen2-gaze-estimation/main.py
The Gaze is incoherent with the pose and eye gaze angle. Additionally the 3d-axis drawn for a pose is distorted and incorrect for most pose angles,
The top line of the following image shows examples of incoherence and distortion, the bottom line is captures at similar times with the fixes in this PR
The comprehension iteration of pose_nn.get().values() is not producing the  required order Yaw, Role,Pitch
Debugger observation shows it is reversed `['angle_p_fc', 'angle_r_fc', 'angle_y_fc']` from the following list comprehension
`                 self.pose = [val[0][0] for val in to_tensor_result(pose_nn.get()).values()]`
As a result the Gaze model being fed with a reversed pose (Pitch, Roll, Yaw)
The 3d Pose Axis indicator is distorted, refactor to the code from OpenVino Open Model Zoo - …
=> fix: incoherent gaze & distorted pose 3d-axis

gen2-multiple-devices/README.md, gen2-multiple-devices/main.py, gen2-multiple-devices/requirements.txt
- Customizes loaded pipeline based on device type: for this simple example, just creates a larger RGB preview size for OAK-D devices (determined by the 3 cameras), vs OAK-1 devices.
- Error-out if no devices are found.
Output example for having connected: OAK-1 on USB2, OAK-D on USB3, OAK-1-POE and OAK-D-POE:
```
Found 4 devices
=== Connected to 14442C10016B5ED700
>>> MXID: 14442C10016B5ED700
>>> Cameras: RGB LEFT RIGHT
>>> USB speed: SUPER
>>> Loading pipeline for: OAK-D
=== Connected to 14442C10D197AACE00
>>> MXID: 14442C10D197AACE00
>>> Cameras: RGB
>>> USB speed: HIGH
>>> Loading pipeline for: OAK-1
[192.168.1.23] [29.087] [system] [warning] Calibration Data on device is empty
=== Connected to 192.168.1.23
>>> MXID: 14442C1031A3A7D200
>>> Cameras: RGB LEFT RIGHT
>>> USB speed: UNKNOWN …
```
=> gen2-multiple-devices: custom pipelines per device type

gen2-road-segmentation/README.md, gen2-road-segmentation/main.py, gen2-road-segmentation/requirements.txt
This PR adds a standalone example of running `road-segmentation-adas-0001` on DepthAI.
Related PR - https://github.com/luxonis/depthai/pull/460
Install requirements
```
python3 -m pip install -r requirements.txt
```
```
python3 main.py
```
This will download the road segmentation model from OpenVINO Model Zoo and perform the inference on RGB camera, together with depth output
=> Add Gen2 Road Segmentation experiment

gen2-human-machine-safety/main.py
Accidentally broke calculation of palm detection centroid in the last PR by forgetting to update a couple of variables. Would be off by 1/3 of input ROI size.
=> gen2-human-machine-safety: fix palm centroid offset

gen2-deeplabv3_person/deeplabv3_person_256.py
I encountered the error below.
> RuntimeError: Device booted with different OpenVINO version that pipeline requires
The error seems to occur if the previous device firmware is different from the model version.
=> specify pipeline in the Device constructor

gen2-record-replay/libraries/depthai_record.py
I noticed that the queue called `depth` was never found.
This was the reason:
`"left" or "disparity" or "depth"` is always equal to `"left"`
`"right" or "disparity" or "depth"`  is always equal to `"right"`
`"disparity" or "depth"`  is always equal to `"disparity"`
The `depth` recording only worked if `left`, `right` and `disparity` were also selected.
=> Depth and disparity pipelines fixed

gen2-calc-spatials-on-host/calc.py
=> Fix X coordinate calculation for spatial calculation on host

gen2-play-encoded-stream/main.py
```
usage: main.py [-h] [-res {4k,13mp,1080,12mp}] [-enc {h264,h265,jpeg}] [-fps FPS] [-v]
options:
-h, --help            show this help message and exit
-res {4k,13mp,1080,12mp}, --resolution {4k,13mp,1080,12mp}
Select color camera resolution. Default: 4k
-enc {h264,h265,jpeg}, --encode {h264,h265,jpeg}
Select encoding format. Default: h264
-fps FPS, --fps FPS   Camera FPS to configure. Default: 30.0
-v, --verbose         Prints latency for the encoded frame data to reach the app
```
Usage example:
`python3 main.py -v -enc jpeg -fps 20.5 -res 1080`
```
Latency: 31.380 ms === 
Latency: 31.249 ms ===    0 aq=    0KB vq=    0KB sq=    0B f=0/0   
Latency: 30.474 ms ===    1 aq=    0KB vq=    0KB sq=    0B f=0/0   
Latency: 30.982 ms ===    1 aq=    0KB vq=    0KB sq=    0B f=0/0   
Latency: …
```
=> gen2-play-encoded-stream: resolution/encoding/FPS config, show latency

gen2-webrtc-streaming/main.py
Small bugfix to accurately fetch the height parameter from the request instead of the width within the `height` property.
=> Bugfix: Height property to get the height param

gen3/neural-networks/basic-example/README.md, gen3/neural-networks/basic-example/main.py, gen3/neural-networks/basic-example/requirements.txt, gen3/neural-networks/basic-example/utils/arguments.py
This PR adds a general experiment that can visualize any `basic` model that is available on HubAI. It uses the new depthai visualizer with the newset available version of depthai-nodes.
To visualize any model, there is a simple CLI interface wher you specify `- s <<slug name from HubAI>>`, optioanlly you can also specify fps and device IP. If no IP is specified, the script will first look for env variable $DEPTHAI_DEVICE_NAME_LIST, if none is provided, the device is chosen randomly by depthai.
=> A general experiment

gen3/neural-networks/basic-example/main.py, gen3/neural-networks/segmentation/basic-example/README.md, gen3/neural-networks/segmentation/basic-example/main.py, gen3/neural-networks/segmentation/basic-example/requirements.txt, gen3/neural-networks/segmentation/basic-example/seg_annotation_node.py, gen3/neural-networks/segmentation/basic-example/utils/arguments.py
This PR adds a general sicript for running all pure segmentation models that is, models that return the message type `dai_nodes.SegmentationMask`, otherwise an exception is raised. The main addition is the annotation node that blends the segmentation mask over the original image frame.
=> Segmentation models example

gen3/neural-networks/segmentation-and-detection/README.md, gen3/neural-networks/segmentation-and-detection/detection_segmentation_node.py, gen3/neural-networks/segmentation-and-detection/main.py, gen3/neural-networks/segmentation-and-detection/requirements.txt, gen3/neural-networks/segmentation-and-detection/utils/arguments.py
This PR adds a general script for running ImgDetectionsExtended that have a segmentation mask attached. Currently it only works on RVC4 as there is an issue with dai.ImgTransformation returning None on RVC2.
=> Img detections extended example

gen3/neural-networks/generic-example/utils/segmentation.py
dding a small fix for the time miss-match between segmentation and detections. Thanks @aljazkonec1 for help!
=>  fix: add timestamp to the DetSegAnntotationNode output

depth-measurement/triangulation/main.py, neural-networks/advanced-examples/counting/crowdcounting/nn_configs.py, neural-networks/advanced-examples/facial-detections/age-gender/main.py, neural-networks/advanced-examples/facial-detections/blur-faces/main.py, neural-networks/advanced-examples/image-matching/xfeat/README.md, neural-networks/advanced-examples/image-matching/xfeat/utils/arguments.py, neural-networks/advanced-examples/pose-estimation/human-pose/README.md, neural-networks/advanced-examples/pose-estimation/human-pose/run_standalone.py, neural-networks/advanced-examples/pose-estimation/human-pose/utils/arguments.py, tutorial/qr-with-tiling/README.md, tutorial/qr-with-tiling/main.py
Adjusting the HubAI model references to the updated names (switching from HxW to WxH naming convention, removing the "NEW" tags). References of the following models were adjusted:
- XFeat
- YuNet
- QRDet
- Lite-HRNet
- CREStereo
The following models were also checked but no direct references are used in the repo:
- MediaPipe Selfie Segmentation
- Zero-DCE
- DnCNN3
- Depth Anything V2
- MiDaS v2.1
- PP-LiteSeg
- eWaSR
=> Fix: HubAI model references

neural-networks/generic-example/main.py, neural-networks/generic-example/requirements.txt, neural-networks/generic-example/utils/segmentation.py
Adjust the generic example to the recent updates in **DAI (3.0.0a13)**:
- `ReplayVideo` node can be used as input to `ParsingNeuralNetwork`;
- host nodes should inherit from `HostNode` instead of `ThreadedHostNode`.
Removed `ImageManip` node after the `ReplayVideo` node, and adjusted the `SegAnnotationNode` and `DetSegAnntotationNode` to inherit from the `HostNode`.
None.
None.
Tested the example on the following models:
- `luxonis/dm-count:shb-426x240` due to past problems with stride;
- `luxonis/rt-super-resolution:50x50` due to past problems with stride;
- `luxonis/deeplab-v3-plus:256x256` for segmentation mode;
- `luxonis/yolov8-instance-segmentation-nano:coco-512x288` for segmentation_with_annotation mode.
=> feat: update generic example

neural-networks/object-detection/yolo-host-decoding/main.py
Add the `setMaxOutputFrameSize` so we can also use 640x640 YOLO for example.
=> Gen3: YOLO-host-decoding - Bug fix.

stream-manipulation/mjpeg-streaming/utils/mjpeg_streamer.py, stream-manipulation/on-device-encoding/README.md, stream-manipulation/on-device-encoding/main.py, stream-manipulation/on-device-encoding/oakapp.toml, stream-manipulation/on-device-encoding/utils/arguments.py, stream-manipulation/rtsp-streaming/README.md, stream-manipulation/rtsp-streaming/oakapp.toml, stream-manipulation/rtsp-streaming/requirements.txt, stream-manipulation/webrtc-streaming/README.md, stream-manipulation/webrtc-streaming/oakapp.toml
Add missing standalone mode to `stream-manipulation` experiments
Tested on RVC4
=> Gen3: Stream manipulation standalone mode

custom-frontend/raw-stream/requirements.txt, depth-measurement/calc-spatial-on-host/requirements.txt, depth-measurement/stereo-on-host/requirements.txt, depth-measurement/triangulation/requirements.txt, neural-networks/3D-detection/objectron/requirements.txt, neural-networks/counting/crowdcounting/requirements.txt, neural-networks/facial-detection/age-gender/requirements.txt, neural-networks/facial-detection/blur-faces/requirements.txt, neural-networks/facial-detection/emotion-recognition/requirements.txt, neural-networks/facial-detection/face-mask-detection/requirements.txt, neural-networks/facial-detection/fatigue-detection/requirements.txt, neural-networks/facial-detection/gaze-estimation/requirements.txt, neural-networks/feature-detection/xfeat/requirements.txt, neural-networks/generic-example/requirements.txt, neural-networks/object-detection/human-machine-safety/requirements.txt, neural-networks/object-detection/social-distancing/requirements.txt, neural-networks/object-detection/spatial-detections/requirements.txt, neural-networks/object-detection/text-blur/requirements.txt, neural-networks/object-detection/thermal-detection/requirements.txt, neural-networks/object-detection/yolo-host-decoding/requirements.txt, neural-networks/object-detection/yolo-p/requirements.txt, neural-networks/object-detection/yolo-world/requirements.txt, neural-networks/pose-estimation/animal-pose/requirements.txt, neural-networks/pose-estimation/hand-pose/requirements.txt, neural-networks/pose-estimation/human-pose/requirements.txt, neural-networks/reidentification/human-reidentification/requirements.txt, neural-networks/segmentation/depth-crop/requirements.txt, stream-manipulation/rtsp-streaming/requirements.txt
Solves the issue with standalone mode introduced in Visualizer version that is present in DepthAI 3.0.0alpha15.
Many `requirements.txt` are change to either pin their current version or use fixed alpha15 snapshot version.
Experiments where the replace with snapshot version was performed were tested. Those where only change was pinning the DepthAI version were not tested as they are expected to be working on the version they were developed for.
=> Fix Gen3: Depthai Version

depth-measurement/stereo-on-host/utils/host_stereo_sgbm.py
Fix of the `stereo-on-host` experiment for RVC4. Since the `getStereo[Left|Right]RectificationRotation` is not supported on RVC4.
The `StereoSGBM` is changing to use `cv2.stereoRectify` instead of `getStereo[Left|Right]RectificationRotation`.
Tested on RVC4 in standalone mode.
=> Fix: Gen3 Stereo On Host

neural-networks/facial-detection/fatigue-detection/utils/arguments.py
Argument was set to 5 instead of 30 by default. 
=> Fatigue detection: Update fps limit argument to 30 FPS

neural-networks/ocr/general-ocr/utils/host_process_detections.py
Under certain circumstances (and for some reason only only on RVC2) depthai would throw `RuntimeError: Cannot denormalize RotatedRect with mixed normalization` . This happened if text was rotated and on the edge of frame, causing one of the corner points to be outside of the frame bounds, leading to mixed precision (one points' coordinates > 1, the rest < 1). For some reason same issue was not replicated on RVC4.
=> remove dai.RotatedRect.denormalize() from general OCR

gen2-rtsp-streaming/gstreamer/requirements.txt
This PR just fixes the requirements.txt for the gstreamer rtsp example where it looked like one of the dependencies was entered incorrectly
=> corrected gen2-rtsp-straming gstreamer requirements.txt

neural-networks/speech-recognition/whisper-tiny-en/utils/annotation_node.py
In PR #689  text annotations for "Press 'r' to record audio" are appended to the previous list of annotations for each new frame. This causes massive lag after a short time. This PR just moves where that text is generated.
=> [FIX] Increasing annotation lag in whisper experiment

neural-networks/face-detection/gaze-estimation/main.py
Fixing the predefined input size for the gaze-estimation model to better match the aspect ratio of the detection models.
Requesting an input size with aspect ratio of `4:3` instead of `1:1` when utilizing the `YuNet` model (input size `320x240`).
None
None
Ran both on RVC2 and RVC4.
=> fix: gaze-estimation predefined input size

tests/test_examples_peripheral.py, tests/test_examples_standalone.py
- Fixed how we setup environment for peripheral tests
- For standalone tests setting custom DAI which might not be compatible with the rest of the requirements.txt will not work
=> Fix custom dai version in peripheral tests

neural-networks/depth-estimation/crestereo-stereo-matching/main.py
Remove iter5-320x240 variant from the supported ones, and set the backend to dsp.
=> CREStereo example update

custom-frontend/dynamic-yolo-world/backend/src/utils/helper_functions.py, neural-networks/object-detection/yolo-world/utils/helper_functions.py
Fixed edge case where padding was not applied correctly in the new `tokenizers` code.
Tested with previously failing example:
`class_names = ["a", "airplane", "refrigerator", "dog", "microwave oven", "cup"]`
=> Fixed padding for yolo-world postprocessing
