luxonis/oak-examples

social-distancing/main.py
Display two images in one window
=> Display two images in one window

gaze-estimation/README.md, gaze-estimation/main.py, gaze-estimation/requirements.txt
Refactored and made it work faster, demo below
[![Gaze Example Demo](https://user-images.githubusercontent.com/5244214/106155937-4fa7bb00-6181-11eb-8c23-21abe12f7fe4.gif)](https://user-images.githubusercontent.com/5244214/106155520-0f483d00-6181-11eb-8b95-a2cb73cc4bac.mp4)
=> Refactor Gaze Estimation example

gen2-tf-image-classification/README.md, gen2-tf-image-classification/main.py, gen2-tf-image-classification/requirements.txt
This example demonstrates how to run a neural network created using [TensorFlow Image Classification tutorial](https://www.tensorflow.org/tutorials/images/classification)
(which one of our community members has put together in [a single Colab Notebook](https://colab.research.google.com/drive/1oNxfvx5jOfcmk1Nx0qavjLN8KtWcLRn6?usp=sharing), even with OpenVINO conversion to .blob)
=> Add TensorFlow image classification example

gen2-human-pose/README.md, gen2-human-pose/main.py, gen2-human-pose/pose.py, gen2-human-pose/requirements.txt
This example demonstrates how to run [Human Pose Estimation Network](https://docs.openvinotoolkit.org/latest/omz_models_intel_human_pose_estimation_0001_description_human_pose_estimation_0001.html) using Gen2 Pipeline Builder.
[![Gen2 Age & Gender recognition](https://user-images.githubusercontent.com/5244214/107493701-35f97100-6b8e-11eb-8b13-02a7a8dbec21.gif)](https://www.youtube.com/watch?v=Py3-dHQymko "Human pose estimation on DepthAI")
TODO:
=> Add pose estimation example

gaze-estimation/main.py
Addresses https://github.com/luxonis/depthai-experiments/issues/54
- Added graceful CTRL+C exit
=> Gaze estimation update

gaze-estimation/main.py
Added missing and needed lazer mode! -)
=> Added lazer mode

gen2-tf-image-classification/README.md, gen2-tf-image-classification/main.py
This PR introduces fixes to the TensorFlow usage example (posted [here](https://github.com/luxonis/depthai-experiments/issues/55#issuecomment-784497863)) that improved the inference results
=> Fix detection results in TF example

gen2-ocr/main.py, gen2-ocr/requirements.txt
Updated depthai lib and code to match latest changes for gen2-ocr.
Should fix #75
=> Gen2 OCR: Update depthai lib to latest

gen2-pedestrian-reidentification/main.py, gen2-pedestrian-reidentification/requirements.txt
Fixes issues with latest codebase.
=> Update gen2-pedestrian-reidentification to latest codebase

gen2-class-saver-jpeg/main.py, gen2-class-saver-jpeg/requirements.txt
=> Update main.py to use recent lib

gen2-wls-filter/main.py
Regarding comments on https://github.com/luxonis/depthai-experiments/pull/83
Fixes #86 
Removed histogram equalization, scaled disparity based on max range (95)
There are still fluctuations, coming from WLS filter which can be seen on raw filtered disparity image.
Depth colorization removed since it doesn't makes sense when we have disparity on hands.
=> Remove histogram equalization, scale disparity based on max range

gen2-human-pose/README.md, gen2-human-pose/main.py, gen2-human-pose/requirements.txt
This PR improves human pose estimation example
[![Gen2 Age & Gender recognition](https://user-images.githubusercontent.com/5244214/110801736-d3bf8900-827d-11eb-934b-9755978f80d9.gif)](https://www.youtube.com/watch?v=1dp2wJ_OqxI "Human pose estimation on DepthAI")
=> Fix and improve human pose estimation example

README.md, gen2-multiple-devices/README.md, gen2-multiple-devices/main.py, gen2-multiple-devices/requirements.txt
Since few of our users have already had questions about this topic, I added demo code for using multiple devices on a host. Copied/edited code from `depthai-python` branch [gen2_try_multi_device](https://github.com/luxonis/depthai-python/blob/gen2_try_multi_device/examples/06_rgb_full_resolution_saver.py). @alex-luxonis hopefully we can delete your branch after we merge this PR.
- After PR we should also reference this demo from our [docs page about this](https://docs.luxonis.com/projects/api/en/latest/tutorials/multiple)
=> [demo] multiple devices on host

gen2-camera-demo/main.py, gen2-camera-demo/requirements.txt
Fixed an issue where some user could not run the code with `-static` argument.
[https://github.com/luxonis/depthai-experiments/commit/c48f5cb](url)
=> Fixed an issue in gen2 camera demo

gen2-spi/requirements.txt, gen2-spi/spatial-location-calculator/README.md, gen2-spi/spatial-location-calculator/main.py, gen2-spi/spatial-mobilenet/README.md, gen2-spi/spatial-mobilenet/main.py
Added `spatial-location-calculator` and `spatial-mobilenet` examples.
Depthai library has been updated to the latest.
Related PR:
https://github.com/luxonis/esp32-spi-message-demo/pull/7
=> Add spatial locations SPI example

gen2-camera-demo/main.py, gen2-camera-demo/requirements.txt
From the following PR: https://github.com/luxonis/depthai-python/pull/229
=> Backport stereo host fixes into experiments

gen2-tf-image-classification/main.py
This is mostly the usability fix. The old code was using 180x180 as a preview and it's very hard to see the results.
=> Fixed the video preview size and also improved the result fonts

gen2-deeplabv3_depth/README.md, gen2-deeplabv3_depth/main.py, gen2-deeplabv3_depth/requirements.txt, gen2-deeplabv3_person/deeplabv3_person_256.py
=> added deeplab + depth cropping experiment

mjpeg-streaming/README.md, mjpeg-streaming/main.py
I made changes to support Gen2.  They are significant, and mostly taken from the 08 - RGB & MobilenetSSD example.
I found the MJPEG streaming didn't work with Firefox or Safari - it works fine with Chrome, and an iOS app called IPCams.
=> Gen2 changes

gen2-efficientDet/README.md, gen2-efficientDet/main.py, gen2-efficientDet/requirements.txt
TODO:
- code clean up 
- try to boost fps (use [this](https://github.com/luxonis/depthai-python/pull/209) branch, compile model for 6 shaves)
- make a proper readme
Demo gif (2x FF):
=> added efficientDet experiment

gen2-spi/two-streams/README.md, gen2-spi/two-streams/main.py
This example shows how to send two different streams through the SPI to the ESP32
ESP32 side code PR: https://github.com/luxonis/esp32-spi-message-demo/pull/8
Gif:
=> Spi two streams demo

gen2-deeplabv3_depth/README.md, gen2-deeplabv3_depth/main.py, gen2-deeplabv3_depth/requirements.txt
- Used color camera with rgb/depth alignment instead of the rectified right stream for NN inference
- New video:
=> Refactor deeplab depth

gen2-deeplabv3_depth/README.md, gen2-deeplabv3_depth/main.py
Added host-side NN sync, removed flickering
=> Deeplab depth host-side sync

gen2-mjpeg-streaming/main.py
This PR adds depth-related info to the streamed frame as long as the depth preview itself
=> Update MJPEG streaming example to stream depth info

gen2-webrtc-streaming/client/index.html, gen2-webrtc-streaming/server.py, gen2-webrtc-streaming/transformators.py
Added depth support to gen2-webrtc-streaming example.
=> added depth support to webrtc-example

gen2-age-gender/README.md, gen2-age-gender/main.py
2nd stage NN should now get the same frame as the 1st stage NN by using frames sequence number in the scripting node.
Working confirmed [on Discord](https://discord.com/channels/790680891252932659/795743863519576105/871795031781040148).
=> Script frame sequence number matching

gen2-collecting-training-data/main.py
This PR addresses this issue: https://github.com/luxonis/depthai-experiments/issues/182
=> Fixed memory leak for collecting training data demo

gen2-triangulation/README.md, gen2-triangulation/main.py, gen2-triangulation/requirements.txt
refactored stereo inference demo so it uses disparity, then calculates depth/spatial coordiantes. Depth/Spatial coordinates seem to be quite accurate.
=> Refactored stereo inference

gen2-human-pose/main.py, gen2-human-pose/requirements.txt, gen2-people-counter/main.py, gen2-people-counter/requirements.txt, gen2-road-segmentation/main.py, gen2-road-segmentation/requirements.txt
This PR migrages `gen2-human-pose`, `gen2-road-segmentation` and `gen2-people-counter` experiments to use DepthAI SDK
Related PR - https://github.com/luxonis/depthai/pull/469
=> Migrate experiments to use DepthAI SDK

gen2-human-machine-safety/main.py
This PR is an updated version of #211, containing both the changes from the mentioned PR and a couple of bug/style fixes
=> Improve human machine safety demo

gen2-blur-faces/README.md, gen2-blur-faces/main.py, gen2-blur-faces/requirements.txt
=> Added blur faces example

gen2-fast-depth/README.md, gen2-fast-depth/main.py, gen2-fast-depth/requirements.txt
Added gen2-fast-depth experiment.
=> Added gen2-fast-depth

gen2-emotion-recognition/README.md, gen2-emotion-recognition/main.py, gen2-emotion-recognition/requirements.txt, gen2-triangulation/README.md, gen2-triangulation/main.py
=> Added face emotions estimation

gen2-collecting-training-data/main.py
As reported [on Discord](https://discord.com/channels/790680891252932659/791009404307767346/908107577966092338), there's problem with multi-thredded env on Windows (also had a problem with record/replay, but that was fixed already).
=> Fixed collecting training data on Windows

gen2-facemesh/main.py
Adds sigmoid on the score and fixes this issue #245
=> [Gen2 Facial Landmarks] Add sigmoid function to score

gen2-car-detection/README.md, gen2-car-detection/download.py, gen2-car-detection/main.py, gen2-car-detection/models/README.txt
Experiment for next steps of YoloV3-tiny and YoloV4-tiny tutorial. It is trained for car detection on [*Annotated driving dataset*](https://github.com/udacity/self-driving-car/tree/master/annotations) from Udacity.
=> Add next steps example for new YoloV3-tiny and YoloV4-tiny tutorial

gen2-lossless-zooming/README.md, gen2-lossless-zooming/main.py, gen2-lossless-zooming/requirements.txt
=> Added lossless zooming demo

gen2-depth-driven-focus/README.md, gen2-depth-driven-focus/main.py, gen2-depth-driven-focus/requirements.txt
=> Depth driven focus

gen2-wls-filter/main.py
Gives better results, eliminates mirrored depth errors
=> Remove right frame flip

README.md, gen2-blur-faces/main.py, gen2-cumulative-object-counting/main.py, gen2-people-tracker/README.md, gen2-people-tracker/main.py, gen2-people-tracker/requirements.txt, gen2-people-tracker/script.py
=> Refactored people tracker to use Script node for tracklets decoding

gen2-multiple-devices/README.md, gen2-multiple-devices/multi-device-mobilenet.py, gen2-multiple-devices/requirements.txt
=> Added object detection running on multiple devices demo

gen2-calc-spatials-on-host/README.md, gen2-calc-spatials-on-host/calc.py, gen2-calc-spatials-on-host/main.py, gen2-calc-spatials-on-host/requirements.txt, gen2-calc-spatials-on-host/utility.py
=> Added spatial calculator example on host side

gen2-maskrcnn-resnet50/README.md, gen2-maskrcnn-resnet50/main.py, gen2-maskrcnn-resnet50/requirements.txt
=> Add Mask R-CNN

gen2-custom-models/generate_model/pytorch_normalize.py
Will come hand-in-hand with this PR: https://github.com/luxonis/depthai-python/pull/388
=> Added custom normalization model

gen2-custom-models/concat.py, gen2-custom-models/requirements.txt
Merge once depthai `2.11` is released. Currently works after running install_requirements.py from [neuralnetwork_multiple_inputs](https://github.com/luxonis/depthai-python/tree/neuralnetwork_multiple_inputs) branch.
=> Multiple inputs for NN node (refactor concat.py custom CV model)

gen2-age-gender/main.py
=> Added spatial coordinates to the age_gender demo

gen2-pipeline-analyser/README.md, gen2-pipeline-analyser/analyse.py, gen2-pipeline-analyser/example_pipeline.json
This experiment prints relevant information about JSON-serialized pipeline. Useful for debug purposes when analysing the pipeline
Script works with just Python3 without any extra dependencies.
To use, run the following command
```
$ python3 analyse.py <path_to_pipeline_json_file>
```
To see an example of the visualization, you can use `example_pipeline.json` file
```
$ python3 analyse.py example_pipeline.json
=== LEVEL 0 ====
XLinkIn
Connections: "out" to MonoCamera "inputControl"
Properties: [185, 3, 189, 12, 108, 101, 102, 116, 95, 99, 111, 110, 116, 114, 111, 108, 129, 0, 4, 8]
XLinkIn
Connections: "out" to MonoCamera "inputControl"
Properties: [185, 3, 189, 13, 114, 105, 103, 104, 116, 95, 99, 111, 110, 116, 114, 111, 108, 129, 0, 4, 8]
XLinkIn
Connections: "out" to ColorCamera …
```
=> Add pipeline JSON analyser script

gen2-full-fov-nn/README.md, gen2-full-fov-nn/main.py, gen2-full-fov-nn/requirements.txt
This demo shows how you can run NN inferencing on full FOV frames
=> Added full fov NN inferencing demo

gen2-fire-detection/main.py, gen2-gaze-estimation/main.py, gen2-head-posture-detection/main.py, gen2-palm-detection/main.py, pcl-projection-rgb/colorized_pont_cloud.py, pcl-projection-rgb/rgbd_creating_no_o3d.py, pcl-projection-rgb/rgbd_creating_o3d.py, stereo_on_host/stereo_on_host.py, stereo_on_host/stereo_test.py
=> Fix for refactored way of node creation

gen2-human-pose/main.py, gen2-road-segmentation/main.py
=> Fixed gen2-human-pose and gen2-road-segmentation

gen2-human-pose/main.py, gen2-road-segmentation/main.py, gen2-yolo/car-detection/main.py
=> Also fixed gen2-yolo/car-detection

gen2-stereo-on-host/main.py
To bring on-device stereo implementation and opencv implementation closer
=> Improve opencv stereo code on host

apps/conference-demos/rgb-depth-detections/README.md
=> Added readme

gen2-qr-code-scanner/README.md, gen2-qr-code-scanner/main.py, gen2-qr-code-scanner/requirements.txt
=> Added QR code detection demo

gen2-age-gender/README.md, gen2-emotion-recognition/README.md, gen2-face-recognition/README.md, gen2-head-posture-detection/README.md, gen2-mask-detection/README.md, gen2-pedestrian-reidentification/README.md
=> Add pipeline graph for some into README of some experiments

.gitignore, gen2-age-gender/main.py, gen2-age-gender/requirements.txt, gen2-emotion-recognition/main.py, gen2-emotion-recognition/requirements.txt, gen2-head-posture-detection/main.py, gen2-head-posture-detection/requirements.txt, gen2-mask-detection/main.py, gen2-mask-detection/requirements.txt, gen2-pedestrian-reidentification/main.py, gen2-pedestrian-reidentification/requirements.txt
=> Fix multi-stage NN demos

gen2-full-fov-nn/README.md, gen2-full-fov-nn/cropping.py, gen2-full-fov-nn/letterboxing.py, gen2-full-fov-nn/stretching.py
=> Updated full-fov-nn demos

gen2-objectron/README.md, gen2-objectron/functions.py, gen2-objectron/main.py, gen2-objectron/requirements.txt, gen2-objectron/script.py
Objectron experiment utilizing Mediapipe's chair model.
Includes:
- Single-object 3D bounding box for chairs in image coordinates
- Depth map and z-coordinate distance to object
=> Objectron Experiment

gen2-box_measurement/box_estimator.py, gen2-box_measurement/main.py, gen2-box_measurement/requirements.txt
Added reverse transformation with visualization of 3D bounding box points to 2D image plane.
=> added reverse transformation from 3D to 2D

gen2-multiple-devices/main.py
OAK cameras now connect in parallel (using threads), which leads to faster bootup time and potentially resolve the issue with connecting oak poe cameras
=> fixed gen2-multiple-devices/main.py 

gen2-anomaly-detection/download.py, gen2-anomaly-detection/main.py, gen2-anomaly-detection/requirements.txt
Anomaly detection experiment using the PaDiM model trained on wood.
=> Anomaly Detection

gen2-deepsort-tracking/deep_sort_realtime/deepsort_tracker.py, gen2-deepsort-tracking/requirements.txt
Commented out the PyTorch dependency.
=> Remove PyTorch dependency

gen2-seven-segment-recognition/README.md, gen2-seven-segment-recognition/download.py, gen2-seven-segment-recognition/main.py, gen2-seven-segment-recognition/requirements.txt, gen2-seven-segment-recognition/utils.py
=> Seven Segment experiment init

gen2-pointcloud/rgbd-pointcloud/README.md, gen2-pointcloud/rgbd-pointcloud/main.py
Add saving and rectified left/right views to rgbd pointcloud script
As per https://github.com/luxonis/depthai-experiments/pull/385#issuecomment-1209532078
=> feat: add saving and rectified views to rgbd-pointcloud

gen2-anomaly-detection/model_export/README.md, gen2-anomaly-detection/model_export/export.py
An example export script to use with anomalib in order to assist with custom model training and reproducibility.
=> Anomalib Model Conversion

gen2-syncing/README.md, gen2-syncing/imu-frames-timestamp-sync.py
Merge together with https://github.com/luxonis/depthai-docs-website/pull/347
=> Updated IMU/depth/rgb syncing demo so it's better fit for VIO solutions

gen2-rerun/README.md, gen2-rerun/pointcloud.py, gen2-rerun/requirements.txt
Added a rerun pointcloud example
=> Gen2 rerun

gen2-nanosam/README.md, gen2-nanosam/decoder.py, gen2-nanosam/requirements.txt, gen2-nanosam/run_keypoints.py, gen2-nanosam/run_yolov6n.py, gen2-nanosam/utils.py
NanoSAM experiment.
Could be further optimized for performance in the future.
=> NanoSAM experiment

gen2-webrtc-streaming/client/package-lock.json, gen2-webrtc-streaming/client/package.json
Aims to solve the critical vulnerabilities:
- #464 
- #503 
Additionally fix #537
=> Fix WebRTC example vulnerability

gen2-poe-tcp-streaming/poe-host-yolo/README.md, gen2-poe-tcp-streaming/poe-host-yolo/host.py, gen2-poe-tcp-streaming/poe-host-yolo/oak.py
Added oak/host python scripts for standalone Yolo model with TCP connection (oak as host)
WIP: add readme, clean up code, write docs (update rvc2 standalone mode docs)
=> Added oak/host python scripts for standalone Yolo 

.github/workflows/run_test.yml
GH Action workflow file for _gen3_ automated testing. 
The workflow has to be in the default branch (_master_) to be visible also on _gen3_ branch.
=> Gen3 Test GH Action Worklflow

neural-networks/README.md
Adding a small fix to the gen2 experiment links.
=> fix: gen2 experiment linking

gen2-anomaly-detection/main.py
See issues here:
https://discuss.luxonis.com/d/5310-gen2-anomaly-detection-example-blob-not-found/5
=> Update yolo from API

README.md, apps/README.md, camera-controls/README.md, conference-demos/README.md, connectivity/README.md, depth-measurement/README.md, stream-manipulation/README.md, tutorial/README.md
Refactoring the root folder README file. The file now provides basic description of each category. Each category then has it's own README with more detailed description and platform compatibility table of category's experiments.
=> ref: Main README

neural-networks/generic-example/README.md, neural-networks/generic-example/main.py
Changing the Generic-Example so that FPS can also be adjusted for media.
=> Gen3: Media FPS in Generic-Example

neural-networks/3D-detection/objectron/main.py, neural-networks/3D-detection/objectron/utils/annotation_node.py, neural-networks/feature-detection/xfeat/mono.py, neural-networks/feature-detection/xfeat/requirements.txt, neural-networks/feature-detection/xfeat/stereo.py, neural-networks/feature-detection/xfeat/utils/custom_visualizer.py, neural-networks/object-detection/yolo-host-decoding/utils/host_decoding.py, neural-networks/object-detection/yolo-p/main.py, neural-networks/object-detection/yolo-p/utils/annotation_node.py, neural-networks/pose-estimation/animal-pose/main.py, neural-networks/pose-estimation/animal-pose/utils/annotation_node.py, neural-networks/pose-estimation/human-pose/main.py, neural-networks/pose-estimation/human-pose/utils/annotation_node.py
This PR switches the `ThreadedHostNode` with `HostNode` and adjust the pipeline.
We also add support for python 3.8 by using types from `typing` e.g. `List`.  
XFeat requirements are updated with new dai-nodes release. Previously, it was installed from github source.
=> Gen3: Switch ThreadedHostNode with HostNode & Py3.8 support.

apps/default-app/main.py, camera-controls/depth-driven-focus/main.py, camera-controls/lossless-zooming/main.py, connectivity/hub-snaps-events/main.py, neural-networks/counting/people-counter/main.py, neural-networks/facial-detection/face-mask-detection/main.py, neural-networks/generic-example/main.py, neural-networks/object-detection/thermal-detection/main.py, neural-networks/object-tracking/people-tracker/main.py, stream-manipulation/mjpeg-streaming/main.py, tutorials/custom-models/blur.py, tutorials/custom-models/concat.py, tutorials/custom-models/diff.py, tutorials/custom-models/edge.py, tutorials/custom-models/main.py, tutorials/play-encoded-stream/main.py, tutorials/play-encoded-stream/opencv.py, tutorials/play-encoded-stream/pyav.py, tutorials/qr-with-tiling/main.py
Get platform information from device without the need to pull the default device from pipeline again. 
=> Get platform information from device

neural-networks/3D-detection/objectron/main.py, neural-networks/pose-estimation/animal-pose/main.py, neural-networks/pose-estimation/hand-pose/main.py, neural-networks/pose-estimation/human-pose/main.py
Uniformly retrieve skeleton pairs from NN archive.
=> Gen3: Retrieve skeleton pairs from NN archive.

README.md
Adds explore button to main README for each category.
Only the main README is changing.
=> Feat Gen3: Main Readme Explore Button

neural-networks/3D-detection/objectron/utils/annotation_node.py
Confidence was not multiplied by 100.
=> Fix: Objectron confidence in percentage.

custom-frontend/raw-stream/.oakappignore, custom-frontend/raw-stream/README.md, custom-frontend/raw-stream/frontend/package-lock.json, custom-frontend/raw-stream/frontend/package.json, custom-frontend/raw-stream/frontend/src/main.tsx, custom-frontend/raw-stream/main.py
=> Fix raw stream example

README.md
=> Added DAIV2 banner

custom-frontend/dynamic-yolo-world/frontend/index.html, custom-frontend/dynamic-yolo-world/frontend/package-lock.json, custom-frontend/dynamic-yolo-world/frontend/package.json, custom-frontend/dynamic-yolo-world/frontend/src/main.tsx
Fix for compatibility with new static frontend hosted on *.luxonis.app
=> fix: yolo world frontend

apps/conference-demos/rgb-depth-connections/backend-run.sh, apps/conference-demos/rgb-depth-connections/oakapp.toml, apps/conference-demos/rgb-depth-connections/requirements.txt, apps/default-app/backend-run.sh, apps/default-app/oakapp.toml
=> feat: oakapp-base integration

neural-networks/depth-estimation/foundation-stereo/main.py
Fix double undistortion for left and right streams
=> set enableUndistortion=False to prevent double undistortion
